version: '3.4'
services:
  mariadb:
    image: mysql:8.0 # mariadb:11.5.2
    ports:
      - "13306:3306"
    command:
      --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_USER: javafxTest
<<<<<<< HEAD
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: worker
=======
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: mydb
>>>>>>> 9756ac914468ccd46795aa86ccd879589283bdde
      MYSQL_USER: javafxTest
      MYSQL_PASSWORD: 1111
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
      - ./init.sql:/data/application/init.sql

    # network_mode: "host"
